### ISSUE TITLE
walls

### ISSUE THREAD

**Issue by udeved** [0ADMods/han_china#11]
Should the han have upgradable walls?
eg start with squashed mud wall upgradable to stone wall?

These Han city walls were pretty gigantic, Beijing walls have a thickness of ~50m!

**Comment by Nescio0** [comment]
Upgradable walls will probably cause problems (rebuilding destroyed segments, different footprints and obstruction size, etc.), but having multiple separate wallsets is perfectly fine; see e.g. the Romans in the public folder.

**Comment by udeved** [comment]
I will merge the rice branch into the gameplay branch.
Walls are now available in village phase and slightly cheaper as the original civ description stated.
I have tested on a map with rmgen2 and a hacked rmgen, walls are also granted on random maps like for the Iberians.
