### ISSUE TITLE
unit "han_champion_chariot" error (delenda_est & hanChina)

### ISSUE THREAD

**Issue by mrlie58** [0ADMods/han_china#16]
ERROR: art/meshes/structural/chin_chariot.dae: Assertion not satisfied (line 393): failed requirement "recognised skeleton structure"

ERROR: Could not load mesh 'art/meshes/structural/chin_chariot.dae'

ERROR: CObjectEntry::BuildVariation(): Model art/meshes/structural/chin_chariot.dae failed to load

**Comment by udeved** [comment]
Do you use the git repo for the mod?
These error messages are thrown for a older version, not the current git version.

You might have to clean the 0ad cache.

**Comment by mrlie58** [comment]
both mods are from github

**Comment by mrlie58** [comment]
When using only HanChina mod (revision 65) and latest svn-version 0ad (revision 23560), the unit "han_champion_chariot" appears without any errors, but then the other "chariot-units" failed:
ERROR: art/meshes/structural/maur_chariot_a.dae: Assertion not satisfied (line 393): failed requirement "recognised skeleton structure"

ERROR: Could not load mesh 'art/meshes/structural/maur_chariot_a.dae'

ERROR: CObjectEntry::BuildVariation(): Model art/meshes/structural/maur_chariot_a.dae failed to load

**Comment by mrlie58** [comment]
it seems to be the file
\0ad\binaries\data\mods\public\art\skeletons\chariot.xml
which is also found in
mods\HanChina\art\skeletons\chariot.xml

when deleting the file in HanChina, all is fine ...

**Comment by udeved** [comment]
I am inclined to close the issue, because it is unrelated to the Han mod.

There are no errors thrown if you use Han mod only. Do not mix with Delenda Est mod.
There is no chariot champion unit in Han mod, only a hero chariot.

**Comment by mrlie58** [comment]
Hi,

 

first it’s correct, there is „han_hero_wei_qing_chariot“, not „han_champion_chariot“, this was only a „write-error“.

 

As i wrote, i only use „0ad“ and HanChina mod.

 

There is a file „chariot.xml“ located in „C:\Users\Me\AppData\Local\0ad\binaries\data\mods\public\art\skeletons\chariot.xml“ and also located in „\Dokumente\My Games\0ad\mods\han_china-master\art\skeletons\chariot.xml“

 

Starting „atlas“ with both files you will get:

 



 

As you can see, „han_hero_wei_qing_chariot“ is here, but trying „maur_champion_chariot“ throws the error shown in the picture above

 

 

After rename the file „chariot.xml“ located in „„\Dokumente\My Games\0ad\mods\han_china-master\art\skeletons\chariot.xml“ or deleting the file, all is fine:

 

ALL „CHARIOT-UNITS“ appears without any error

 

 




Maybe „it is unrelated to the Han mod“, but it is related tot he file „chariot.xml“ located in the Han mod.

 

For me it’s not a problem, i just solved it by deleting the file „chariot.xml“ in the Han mod.

I only want give you a tip. I researched this error a long time, because i love 0ad and HanChina 😉

 

Kind regards

 

An old „german bag“ 😉

 

 

Von: artoo <notifications@github.com> 
Gesendet: Donnerstag, 2. April 2020 08:35

An: 0ADMods/han_china <han_china@noreply.github.com>
Cc: mrlie58 <erhard.lipinski@freenet.de>; Author <author@noreply.github.com>
Betreff: Re: [0ADMods/han_china] unit "han_champion_chariot" error (delenda_est & hanChina) (#16)

 

I am inclined to close the issue, because it is unrelated to the Han mod.

There are no errors thrown if you use Han mod only. Do not mix with Delenda Est mod.
There is no chariot champion unit in Han mod, only a hero chariot.

**Comment by udeved** [comment]
If there are errors throw for other chariots, that's not a Han mod problem, but in the public mod.
Han does not alter public mod data.
