### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by udeved** [0ADMods/han_china#18]
@Nescio0 

Would be cool if you used a branch for such changes.
I don't quite agree with some of the changes.

1. Rice should be a unique technology and food source. Xiongnu hardly capture rice fields, they are nomads.
Similarly, any american civ should have eg mais as a unique tech. Imagine Brits captured rice fields, would they have the knowhow and tech immediately to make use of it? Its not realistic, apart from eventual climate differences the game engine doesn't feature.

2. Bolt towers, Han china had extra ordinarily fortified cities, very thick walls and heavily fortifies and defended. They had the tech for big artillery like crossbows to defend cities and against cavalry.

**Comment by udeved** [comment]
My point would be, and my biggest criticism on 0AD, there is more or less only one civ differently skinned. The civs lack uniqueness. Take Starcraft as example, you got only 3 civs, but they play totally different, which is cool.

**Comment by Nescio0** [comment]
@udeved, my priority is on making the mod fully compatible with the public mod of the development version.

As for the reasons for disabling the rice subtype, see the 498061f345a6feb4eea04e9aef183ff7301b3ca7 commit message:
>Don't introduce rice resource subtype:
>* This is not compatible with the public mod.
>* Making it only available to Han China means their fields are useless when captured by other civs, whereas the reverse is not true.
>* Zapotecs don't have a food.maize resource either.
>* food.grain does not represent only wheat, but also other grains:
>    cereals (e.g. barley, oats, rye, spelt, sorghum, millet, maize, and yes, rice)
>    pseudocereals (e.g. buckwheat, quinoa)
>    pulses (beans, chickpeas, lentils, peas).


>My point would be, and my biggest criticism on 0AD, there is more or less only one civ differently skinned. The civs lack uniqueness. Take Starcraft as example, you got only 3 civs, but they play totally different, which is cool.
I don't disagree with you. However, such things should be gradually changed in the development version.
