### ISSUE TITLE
Issues with Chariot

### ISSUE THREAD

**Issue by mrlie58** [0ADMods/han_china#20]
1. Using `...\My Games\0ad\mods\han_china\art\skeletons\chariot.xml` causes errors for all other chariot-units from the Main-Game, you have do delete this and use the `chariot.xml` from the Main-Game
Edit:
deleting `chariot.xml` from han_china causes error for `han_hero_wei_qing_chariot`:
![grafik](https://user-images.githubusercontent.com/60375368/87873664-b45cae80-c9c3-11ea-9288-6af79e298719.png)
leaving `chariot.xml` from han_china causes error for all chariot-units from Main game:
![grafik](https://user-images.githubusercontent.com/60375368/87873711-f84fb380-c9c3-11ea-841d-baded2c97807.png)
renaming `chariot.xml` from han_china to `#chariot.xml` causes no errors for all chariot-units from Main game and han_china.
Atlas reading both `*chariot.xml` files:
![grafik](https://user-images.githubusercontent.com/60375368/87873774-714f0b00-c9c4-11ea-970a-32b1e16df34d.png)
Merge both `chariot.xml` into one also works for me.

2. the chariot-cart cuts the horses
<img width="811" alt="han_chariot" src="https://user-images.githubusercontent.com/60375368/87854012-e52edc00-c90e-11ea-90f3-815a61f9e324.png">

3. the animation `death` of the chariot is broken
https://youtu.be/x2whAIuhDfw

4. all crossbowman do not fetch an arrow while reloading
https://youtu.be/zboIvgslbbY

**Comment by StanleySweet** [comment]
This is fixed now
