### ISSUE TITLE
Use a historically correct bixie

### ISSUE THREAD

**Issue by StanleySweet** [0ADMods/han_china#53]
Concerned buildings, glory statue in delenda est, gov center, civ center
![image](https://user-images.githubusercontent.com/6837402/40143904-10594592-595d-11e8-8cc3-9e104a437972.png)

![image](https://user-images.githubusercontent.com/6837402/40143884-fd2cddc6-595c-11e8-90ee-7011af780113.png)

Courtesy of @lastrodamo
![0ad_han_bixie-01](https://user-images.githubusercontent.com/10653143/133149968-73b533ad-62a6-418e-9455-f1c631ba4ec8.png)

High poly version [statue_bixie-00.zip](https://github.com/0ADMods/terra_magna/files/7728981/statue_bixie-00.zip)

(CC-BY-SA 3.0 Unported)

**Comment by lastrodamo** [comment]
I finalise the Bixie statue low poly with 1053 tris and albedo texture.
![0ad_han_bixie-02](https://user-images.githubusercontent.com/10653143/146675287-2b7f4cfe-1b8e-46d6-ae65-e4bacf3660ad.png)

**Comment by StanleySweet** [comment]
@lastrodamo thanks again, can you make the stone and gold variant please? 

Also upload normal map and spec map :)

**Comment by lastrodamo** [comment]
@StanleySweet I create the textures of Gold, Marble, and Stone version of this Han Bixie.
Available on this link
[https://3dminfographie.com/images/graphisme-3d/0ad/han_bixie/han_bixie_statue_blend-02.zip](url)
